# ──────────────────────────────────────────────────────────────────────────────
# Base Configuration
# ──────────────────────────────────────────────────────────────────────────────
baseURL: "https://syhya.github.io/"
title: "Yue Shui Blog"
pagination:
  pagerSize: 5
theme: ["PaperMod"]

# Default Language Code
languageCode: "en-us"

publishDir: "public"

# Site build options
enableGitInfo: false          # 使用 git 最近一次 commit 作为 .Lastmod
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableInlineShortcodes: true
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]

minify:
  disableXML: true
  minifyOutput: true

# Disable RSS (except where explicitly enabled)
disableKinds:
  - RSS

googleAnalytics: "G-SZ2660B91F"

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

# ──────────────────────────────────────────────────────────────────────────────
# Math & Markup
# ──────────────────────────────────────────────────────────────────────────────
markup:
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2
  goldmark:
    duplicateResourceFiles: false
    extensions:
      cjk:
        eastAsianLineBreaks: false
        eastAsianLineBreaksStyle: simple
        enable: false
        escapedSpace: false
      definitionList: true
      extras:
        delete:
          enable: false
        insert:
          enable: false
        mark:
          enable: false
        subscript:
          enable: false
        superscript:
          enable: false
      footnote: true
      linkify: true
      linkifyProtocol: https
      passthrough:
        delimiters:
          block:
            - - \[
              - \]
            - - $$
              - $$
          inline:
            - - \(
              - \)
        enable: true
      strikethrough: true
      table: true
      taskList: true
      typographer:
        apostrophe: '&rsquo;'
        disable: false
        ellipsis: '&hellip;'
        emDash: '&mdash;'
        enDash: '&ndash;'
        leftAngleQuote: '&laquo;'
        leftDoubleQuote: '&ldquo;'
        leftSingleQuote: '&lsquo;'
        rightAngleQuote: '&raquo;'
        rightDoubleQuote: '&rdquo;'
        rightSingleQuote: '&rsquo;'
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderHooks:
      image:
        useEmbedded: never
      link:
        useEmbedded: never
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false

# ──────────────────────────────────────────────────────────────────────────────
# Multilingual Configuration
# ──────────────────────────────────────────────────────────────────────────────
languages:
  en:
    languageName: "English"
    weight: 1
    contentDir: "content/en"
    languageCode: "en-us"
    title: "Yue Shui Blog"

    params:
      fancybox: true
      math: true
      env: production
      title: "Yue Shui Blog"
      description: "Yue Shui’s personal blog exploring cutting-edge LLM technologies and research papers, with a focus on models, algorithms, and engineering."
      keywords: [Blog, Portfolio, PaperMod]
      author: "Yue Shui"

      images: []

      DateFormat: "2006-01-02"
      ShowLastMod: true
      ShowLastModInList: true

      defaultTheme: auto
      disableThemeToggle: false

      ShowReadingTime: true
      ShowWordCount: true
      ShowShareButtons: true
      ShowPostNavLinks: true
      ShowBreadCrumbs: true
      ShowCodeCopyButtons: true
      ShowRssButtonInSectionTermList: true
      UseHugoToc: true
      showtoc: true
      tocopen: false
      disableSpecial1stPost: false
      disableScrollToTop: false
      comments: true
      hidemeta: false
      hideSummary: false

      label:
        text: "Home"
        icon: /apple-touch-icon.png
        iconHeight: 35

      profileMode:
        enabled: false
        title: "ExampleSite"
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: "my image"
        buttons:
          - name: "Posts"
            url: "posts"
          - name: "Tags"
            url: "tags"

      homeInfoParams:
        Title: "👋 Welcome to Yue's blog"
        Content: "Hi, this is Yue Shui. I’m currently working on LLM algorithms, with a focus on Agentic RL. My past experience includes researching and applying LLMs in fields such as finance, audit, and code generation. This blog is where I document and share insights from my work and learning journey. The grammar mistakes in the posts might give you a hint about ChatGPT’s involvement 😉—let me know if you spot any! My interests include model training, RAG, and LLM Agent. Feel free to connect!"

      socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/yue-shui/"
        - name: github
          url: "https://github.com/syhya"
        - name: email
          url: "mailto:syhya925666582@gmail.com"

      analytics:
        google:
          SiteVerificationTag: "XYZabc"
        bing:
          SiteVerificationTag: "XYZabc"
        yandex:
          SiteVerificationTag: "XYZabc"

      cover:
        hidden: true
        hiddenInList: true
        hiddenInSingle: true

      fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        limit: 10
        keys: ["title", "permalink", "summary", "content"]

      contact:
        email: "syhya925666582@gmail.com"

    menu:
      main:
        - name: Archive
          url: /archives/
          weight: 5
        - name: Search
          url: /search/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20

  zh:
    languageName: "简体中文"
    weight: 2
    contentDir: "content/zh"
    languageCode: "zh-cn"
    title: "Yue Shui 博客"
    hasCJKLanguage: true

    params:
      fancybox: true
      math: true
      env: production
      title: "Yue Shui 博客"
      description: "Yue Shui 的个人博客，专注前沿 LLM 技术与研究论文分享，关注模型、算法与工程。"
      keywords: [博客, 作品集, PaperMod]
      author: "Yue Shui"

      images: []

      DateFormat: "2006-01-02"
      ShowLastMod: true
      ShowLastModInList: true

      defaultTheme: auto
      disableThemeToggle: false

      ShowReadingTime: true
      ShowWordCount: true
      ShowShareButtons: true
      ShowPostNavLinks: true
      ShowBreadCrumbs: true
      ShowCodeCopyButtons: true
      ShowRssButtonInSectionTermList: true
      UseHugoToc: true
      showtoc: true
      tocopen: false
      disableSpecial1stPost: false
      disableScrollToTop: false
      comments: true
      hidemeta: false
      hideSummary: false

      label:
        text: "首页"
        icon: /apple-touch-icon.png
        iconHeight: 35

      profileMode:
        enabled: false
        title: "示例网站"
        subtitle: "这是副标题"
        imageUrl: "<图片位置>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: "我的图片"
        buttons:
          - name: "帖子"
            url: "posts"
          - name: "标签"
            url: "tags"

      homeInfoParams:
        Title: "👋 欢迎访问我的博客"
        Content: "你好，我是 Yue Shui，目前从事大模型算法相关工作，研究方向为 Agentic RL。我的过往经历包括将 LLM 应用于金融、审计和代码生成等领域。这个博客用于记录和分享我在工作与学习中的见解。文章中的语法错误或许能透露出 ChatGPT 的参与程度😉——记得告诉我！我的兴趣包括模型训练、RAG 以及 LLM Agent。欢迎交流！"

      socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/yue-shui/"
        - name: github
          url: "https://github.com/syhya"
        - name: email
          url: "mailto:syhya925666582@gmail.com"

      analytics:
        google:
          SiteVerificationTag: "XYZabc"
        bing:
          SiteVerificationTag: "XYZabc"
        yandex:
          SiteVerificationTag: "XYZabc"

      cover:
        hidden: true
        hiddenInList: true
        hiddenInSingle: true

      fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        limit: 10
        keys: ["title", "permalink", "summary", "content"]

      contact:
        email: "syhya925666582@gmail.com"

    menu:
      main:
        - name: 归档
          url: /archives/
          weight: 5
        - name: 搜索
          url: /search/
          weight: 10
        - identifier: tags
          name: 标签
          url: /tags/
          weight: 20
