baseURL = 'https://syhya.github.io/'
languageCode = 'en-us'
title = 'Yue Shui Blog'
theme = "PaperMod"
[params]
  subtitle = 'The Best Widgets on Earth'
  [params.contact]
    email = 'syhya925666582@gmail.com'